// megafunction wizard: %LPM_MUX%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: LPM_MUX 

// ============================================================
// File Name: Chowdhury_LPM_1Bit64x1Mux_Dec7.v
// Megafunction Name(s):
// 			LPM_MUX
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 16.0.0 Build 211 04/27/2016 SJ Lite Edition
// ************************************************************


//Copyright (C) 1991-2016 Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus Prime License Agreement,
//the Altera MegaCore Function License Agreement, or other 
//applicable license agreement, including, without limitation, 
//that your use is for the sole purpose of programming logic 
//devices manufactured by Altera and sold by Altera or its 
//authorized distributors.  Please refer to the applicable 
//agreement for further details.


//lpm_mux DEVICE_FAMILY="Cyclone V" LPM_SIZE=64 LPM_WIDTH=1 LPM_WIDTHS=6 data result sel
//VERSION_BEGIN 16.0 cbx_lpm_mux 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = lut 21 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  Chowdhury_LPM_1Bit64x1Mux_Dec7_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [63:0]  data;
	output   [0:0]  result;
	input   [5:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [63:0]  data;
	tri0   [5:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	wire_l1_w0_n0_mux_dataout;
	wire	wire_l1_w0_n10_mux_dataout;
	wire	wire_l1_w0_n11_mux_dataout;
	wire	wire_l1_w0_n12_mux_dataout;
	wire	wire_l1_w0_n13_mux_dataout;
	wire	wire_l1_w0_n14_mux_dataout;
	wire	wire_l1_w0_n15_mux_dataout;
	wire	wire_l1_w0_n16_mux_dataout;
	wire	wire_l1_w0_n17_mux_dataout;
	wire	wire_l1_w0_n18_mux_dataout;
	wire	wire_l1_w0_n19_mux_dataout;
	wire	wire_l1_w0_n1_mux_dataout;
	wire	wire_l1_w0_n20_mux_dataout;
	wire	wire_l1_w0_n21_mux_dataout;
	wire	wire_l1_w0_n22_mux_dataout;
	wire	wire_l1_w0_n23_mux_dataout;
	wire	wire_l1_w0_n24_mux_dataout;
	wire	wire_l1_w0_n25_mux_dataout;
	wire	wire_l1_w0_n26_mux_dataout;
	wire	wire_l1_w0_n27_mux_dataout;
	wire	wire_l1_w0_n28_mux_dataout;
	wire	wire_l1_w0_n29_mux_dataout;
	wire	wire_l1_w0_n2_mux_dataout;
	wire	wire_l1_w0_n30_mux_dataout;
	wire	wire_l1_w0_n31_mux_dataout;
	wire	wire_l1_w0_n3_mux_dataout;
	wire	wire_l1_w0_n4_mux_dataout;
	wire	wire_l1_w0_n5_mux_dataout;
	wire	wire_l1_w0_n6_mux_dataout;
	wire	wire_l1_w0_n7_mux_dataout;
	wire	wire_l1_w0_n8_mux_dataout;
	wire	wire_l1_w0_n9_mux_dataout;
	wire	wire_l2_w0_n0_mux_dataout;
	wire	wire_l2_w0_n10_mux_dataout;
	wire	wire_l2_w0_n11_mux_dataout;
	wire	wire_l2_w0_n12_mux_dataout;
	wire	wire_l2_w0_n13_mux_dataout;
	wire	wire_l2_w0_n14_mux_dataout;
	wire	wire_l2_w0_n15_mux_dataout;
	wire	wire_l2_w0_n1_mux_dataout;
	wire	wire_l2_w0_n2_mux_dataout;
	wire	wire_l2_w0_n3_mux_dataout;
	wire	wire_l2_w0_n4_mux_dataout;
	wire	wire_l2_w0_n5_mux_dataout;
	wire	wire_l2_w0_n6_mux_dataout;
	wire	wire_l2_w0_n7_mux_dataout;
	wire	wire_l2_w0_n8_mux_dataout;
	wire	wire_l2_w0_n9_mux_dataout;
	wire	wire_l3_w0_n0_mux_dataout;
	wire	wire_l3_w0_n1_mux_dataout;
	wire	wire_l3_w0_n2_mux_dataout;
	wire	wire_l3_w0_n3_mux_dataout;
	wire	wire_l3_w0_n4_mux_dataout;
	wire	wire_l3_w0_n5_mux_dataout;
	wire	wire_l3_w0_n6_mux_dataout;
	wire	wire_l3_w0_n7_mux_dataout;
	wire	wire_l4_w0_n0_mux_dataout;
	wire	wire_l4_w0_n1_mux_dataout;
	wire	wire_l4_w0_n2_mux_dataout;
	wire	wire_l4_w0_n3_mux_dataout;
	wire	wire_l5_w0_n0_mux_dataout;
	wire	wire_l5_w0_n1_mux_dataout;
	wire	wire_l6_w0_n0_mux_dataout;
	wire  [125:0]  data_wire;
	wire  [0:0]  result_wire_ext;
	wire  [35:0]  sel_wire;

	assign		wire_l1_w0_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[1] : data_wire[0];
	assign		wire_l1_w0_n10_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[21] : data_wire[20];
	assign		wire_l1_w0_n11_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[23] : data_wire[22];
	assign		wire_l1_w0_n12_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[25] : data_wire[24];
	assign		wire_l1_w0_n13_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[27] : data_wire[26];
	assign		wire_l1_w0_n14_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[29] : data_wire[28];
	assign		wire_l1_w0_n15_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[31] : data_wire[30];
	assign		wire_l1_w0_n16_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[33] : data_wire[32];
	assign		wire_l1_w0_n17_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[35] : data_wire[34];
	assign		wire_l1_w0_n18_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[37] : data_wire[36];
	assign		wire_l1_w0_n19_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[39] : data_wire[38];
	assign		wire_l1_w0_n1_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[3] : data_wire[2];
	assign		wire_l1_w0_n20_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[41] : data_wire[40];
	assign		wire_l1_w0_n21_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[43] : data_wire[42];
	assign		wire_l1_w0_n22_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[45] : data_wire[44];
	assign		wire_l1_w0_n23_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[47] : data_wire[46];
	assign		wire_l1_w0_n24_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[49] : data_wire[48];
	assign		wire_l1_w0_n25_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[51] : data_wire[50];
	assign		wire_l1_w0_n26_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[53] : data_wire[52];
	assign		wire_l1_w0_n27_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[55] : data_wire[54];
	assign		wire_l1_w0_n28_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[57] : data_wire[56];
	assign		wire_l1_w0_n29_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[59] : data_wire[58];
	assign		wire_l1_w0_n2_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[5] : data_wire[4];
	assign		wire_l1_w0_n30_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[61] : data_wire[60];
	assign		wire_l1_w0_n31_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[63] : data_wire[62];
	assign		wire_l1_w0_n3_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[7] : data_wire[6];
	assign		wire_l1_w0_n4_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[9] : data_wire[8];
	assign		wire_l1_w0_n5_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[11] : data_wire[10];
	assign		wire_l1_w0_n6_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[13] : data_wire[12];
	assign		wire_l1_w0_n7_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[15] : data_wire[14];
	assign		wire_l1_w0_n8_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[17] : data_wire[16];
	assign		wire_l1_w0_n9_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[19] : data_wire[18];
	assign		wire_l2_w0_n0_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[65] : data_wire[64];
	assign		wire_l2_w0_n10_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[85] : data_wire[84];
	assign		wire_l2_w0_n11_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[87] : data_wire[86];
	assign		wire_l2_w0_n12_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[89] : data_wire[88];
	assign		wire_l2_w0_n13_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[91] : data_wire[90];
	assign		wire_l2_w0_n14_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[93] : data_wire[92];
	assign		wire_l2_w0_n15_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[95] : data_wire[94];
	assign		wire_l2_w0_n1_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[67] : data_wire[66];
	assign		wire_l2_w0_n2_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[69] : data_wire[68];
	assign		wire_l2_w0_n3_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[71] : data_wire[70];
	assign		wire_l2_w0_n4_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[73] : data_wire[72];
	assign		wire_l2_w0_n5_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[75] : data_wire[74];
	assign		wire_l2_w0_n6_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[77] : data_wire[76];
	assign		wire_l2_w0_n7_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[79] : data_wire[78];
	assign		wire_l2_w0_n8_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[81] : data_wire[80];
	assign		wire_l2_w0_n9_mux_dataout = (sel_wire[7] === 1'b1) ? data_wire[83] : data_wire[82];
	assign		wire_l3_w0_n0_mux_dataout = (sel_wire[14] === 1'b1) ? data_wire[97] : data_wire[96];
	assign		wire_l3_w0_n1_mux_dataout = (sel_wire[14] === 1'b1) ? data_wire[99] : data_wire[98];
	assign		wire_l3_w0_n2_mux_dataout = (sel_wire[14] === 1'b1) ? data_wire[101] : data_wire[100];
	assign		wire_l3_w0_n3_mux_dataout = (sel_wire[14] === 1'b1) ? data_wire[103] : data_wire[102];
	assign		wire_l3_w0_n4_mux_dataout = (sel_wire[14] === 1'b1) ? data_wire[105] : data_wire[104];
	assign		wire_l3_w0_n5_mux_dataout = (sel_wire[14] === 1'b1) ? data_wire[107] : data_wire[106];
	assign		wire_l3_w0_n6_mux_dataout = (sel_wire[14] === 1'b1) ? data_wire[109] : data_wire[108];
	assign		wire_l3_w0_n7_mux_dataout = (sel_wire[14] === 1'b1) ? data_wire[111] : data_wire[110];
	assign		wire_l4_w0_n0_mux_dataout = (sel_wire[21] === 1'b1) ? data_wire[113] : data_wire[112];
	assign		wire_l4_w0_n1_mux_dataout = (sel_wire[21] === 1'b1) ? data_wire[115] : data_wire[114];
	assign		wire_l4_w0_n2_mux_dataout = (sel_wire[21] === 1'b1) ? data_wire[117] : data_wire[116];
	assign		wire_l4_w0_n3_mux_dataout = (sel_wire[21] === 1'b1) ? data_wire[119] : data_wire[118];
	assign		wire_l5_w0_n0_mux_dataout = (sel_wire[28] === 1'b1) ? data_wire[121] : data_wire[120];
	assign		wire_l5_w0_n1_mux_dataout = (sel_wire[28] === 1'b1) ? data_wire[123] : data_wire[122];
	assign		wire_l6_w0_n0_mux_dataout = (sel_wire[35] === 1'b1) ? data_wire[125] : data_wire[124];
	assign
		data_wire = {wire_l5_w0_n1_mux_dataout, wire_l5_w0_n0_mux_dataout, wire_l4_w0_n3_mux_dataout, wire_l4_w0_n2_mux_dataout, wire_l4_w0_n1_mux_dataout, wire_l4_w0_n0_mux_dataout, wire_l3_w0_n7_mux_dataout, wire_l3_w0_n6_mux_dataout, wire_l3_w0_n5_mux_dataout, wire_l3_w0_n4_mux_dataout, wire_l3_w0_n3_mux_dataout, wire_l3_w0_n2_mux_dataout, wire_l3_w0_n1_mux_dataout, wire_l3_w0_n0_mux_dataout, wire_l2_w0_n15_mux_dataout, wire_l2_w0_n14_mux_dataout, wire_l2_w0_n13_mux_dataout, wire_l2_w0_n12_mux_dataout, wire_l2_w0_n11_mux_dataout, wire_l2_w0_n10_mux_dataout, wire_l2_w0_n9_mux_dataout, wire_l2_w0_n8_mux_dataout, wire_l2_w0_n7_mux_dataout, wire_l2_w0_n6_mux_dataout, wire_l2_w0_n5_mux_dataout, wire_l2_w0_n4_mux_dataout, wire_l2_w0_n3_mux_dataout, wire_l2_w0_n2_mux_dataout, wire_l2_w0_n1_mux_dataout, wire_l2_w0_n0_mux_dataout, wire_l1_w0_n31_mux_dataout, wire_l1_w0_n30_mux_dataout, wire_l1_w0_n29_mux_dataout, wire_l1_w0_n28_mux_dataout, wire_l1_w0_n27_mux_dataout, wire_l1_w0_n26_mux_dataout, wire_l1_w0_n25_mux_dataout, wire_l1_w0_n24_mux_dataout, wire_l1_w0_n23_mux_dataout, wire_l1_w0_n22_mux_dataout, wire_l1_w0_n21_mux_dataout, wire_l1_w0_n20_mux_dataout, wire_l1_w0_n19_mux_dataout, wire_l1_w0_n18_mux_dataout, wire_l1_w0_n17_mux_dataout, wire_l1_w0_n16_mux_dataout, wire_l1_w0_n15_mux_dataout, wire_l1_w0_n14_mux_dataout, wire_l1_w0_n13_mux_dataout, wire_l1_w0_n12_mux_dataout, wire_l1_w0_n11_mux_dataout, wire_l1_w0_n10_mux_dataout, wire_l1_w0_n9_mux_dataout, wire_l1_w0_n8_mux_dataout, wire_l1_w0_n7_mux_dataout, wire_l1_w0_n6_mux_dataout, wire_l1_w0_n5_mux_dataout, wire_l1_w0_n4_mux_dataout, wire_l1_w0_n3_mux_dataout, wire_l1_w0_n2_mux_dataout, wire_l1_w0_n1_mux_dataout, wire_l1_w0_n0_mux_dataout, data},
		result = result_wire_ext,
		result_wire_ext = {wire_l6_w0_n0_mux_dataout},
		sel_wire = {sel[5], {6{1'b0}}, sel[4], {6{1'b0}}, sel[3], {6{1'b0}}, sel[2], {6{1'b0}}, sel[1], {6{1'b0}}, sel[0]};
endmodule //Chowdhury_LPM_1Bit64x1Mux_Dec7_mux
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module Chowdhury_LPM_1Bit64x1Mux_Dec7 (
	data0,
	data1,
	data10,
	data11,
	data12,
	data13,
	data14,
	data15,
	data16,
	data17,
	data18,
	data19,
	data2,
	data20,
	data21,
	data22,
	data23,
	data24,
	data25,
	data26,
	data27,
	data28,
	data29,
	data3,
	data30,
	data31,
	data32,
	data33,
	data34,
	data35,
	data36,
	data37,
	data38,
	data39,
	data4,
	data40,
	data41,
	data42,
	data43,
	data44,
	data45,
	data46,
	data47,
	data48,
	data49,
	data5,
	data50,
	data51,
	data52,
	data53,
	data54,
	data55,
	data56,
	data57,
	data58,
	data59,
	data6,
	data60,
	data61,
	data62,
	data63,
	data7,
	data8,
	data9,
	sel,
	result)/* synthesis synthesis_clearbox = 1 */;

	input	  data0;
	input	  data1;
	input	  data10;
	input	  data11;
	input	  data12;
	input	  data13;
	input	  data14;
	input	  data15;
	input	  data16;
	input	  data17;
	input	  data18;
	input	  data19;
	input	  data2;
	input	  data20;
	input	  data21;
	input	  data22;
	input	  data23;
	input	  data24;
	input	  data25;
	input	  data26;
	input	  data27;
	input	  data28;
	input	  data29;
	input	  data3;
	input	  data30;
	input	  data31;
	input	  data32;
	input	  data33;
	input	  data34;
	input	  data35;
	input	  data36;
	input	  data37;
	input	  data38;
	input	  data39;
	input	  data4;
	input	  data40;
	input	  data41;
	input	  data42;
	input	  data43;
	input	  data44;
	input	  data45;
	input	  data46;
	input	  data47;
	input	  data48;
	input	  data49;
	input	  data5;
	input	  data50;
	input	  data51;
	input	  data52;
	input	  data53;
	input	  data54;
	input	  data55;
	input	  data56;
	input	  data57;
	input	  data58;
	input	  data59;
	input	  data6;
	input	  data60;
	input	  data61;
	input	  data62;
	input	  data63;
	input	  data7;
	input	  data8;
	input	  data9;
	input	[5:0]  sel;
	output	  result;

	wire [0:0] sub_wire65;
	wire  sub_wire64 = data0;
	wire  sub_wire63 = data1;
	wire  sub_wire62 = data2;
	wire  sub_wire61 = data3;
	wire  sub_wire60 = data4;
	wire  sub_wire59 = data5;
	wire  sub_wire58 = data6;
	wire  sub_wire57 = data7;
	wire  sub_wire56 = data8;
	wire  sub_wire55 = data9;
	wire  sub_wire54 = data10;
	wire  sub_wire53 = data11;
	wire  sub_wire52 = data12;
	wire  sub_wire51 = data13;
	wire  sub_wire50 = data14;
	wire  sub_wire49 = data15;
	wire  sub_wire48 = data16;
	wire  sub_wire47 = data17;
	wire  sub_wire46 = data18;
	wire  sub_wire45 = data19;
	wire  sub_wire44 = data20;
	wire  sub_wire43 = data21;
	wire  sub_wire42 = data22;
	wire  sub_wire41 = data23;
	wire  sub_wire40 = data24;
	wire  sub_wire39 = data25;
	wire  sub_wire38 = data26;
	wire  sub_wire37 = data27;
	wire  sub_wire36 = data28;
	wire  sub_wire35 = data29;
	wire  sub_wire34 = data30;
	wire  sub_wire33 = data31;
	wire  sub_wire32 = data32;
	wire  sub_wire31 = data33;
	wire  sub_wire30 = data34;
	wire  sub_wire29 = data35;
	wire  sub_wire28 = data36;
	wire  sub_wire27 = data37;
	wire  sub_wire26 = data38;
	wire  sub_wire25 = data39;
	wire  sub_wire24 = data40;
	wire  sub_wire23 = data41;
	wire  sub_wire22 = data42;
	wire  sub_wire21 = data43;
	wire  sub_wire20 = data44;
	wire  sub_wire19 = data45;
	wire  sub_wire18 = data46;
	wire  sub_wire17 = data47;
	wire  sub_wire16 = data48;
	wire  sub_wire15 = data49;
	wire  sub_wire14 = data50;
	wire  sub_wire13 = data51;
	wire  sub_wire12 = data52;
	wire  sub_wire11 = data53;
	wire  sub_wire10 = data54;
	wire  sub_wire9 = data55;
	wire  sub_wire8 = data56;
	wire  sub_wire7 = data57;
	wire  sub_wire6 = data58;
	wire  sub_wire5 = data59;
	wire  sub_wire4 = data60;
	wire  sub_wire3 = data61;
	wire  sub_wire2 = data62;
	wire  sub_wire0 = data63;
	wire [63:0] sub_wire1 = {sub_wire64, sub_wire63, sub_wire62, sub_wire61, sub_wire60, sub_wire59, sub_wire58, sub_wire57, sub_wire56, sub_wire55, sub_wire54, sub_wire53, sub_wire52, sub_wire51, sub_wire50, sub_wire49, sub_wire48, sub_wire47, sub_wire46, sub_wire45, sub_wire44, sub_wire43, sub_wire42, sub_wire41, sub_wire40, sub_wire39, sub_wire38, sub_wire37, sub_wire36, sub_wire35, sub_wire34, sub_wire33, sub_wire32, sub_wire31, sub_wire30, sub_wire29, sub_wire28, sub_wire27, sub_wire26, sub_wire25, sub_wire24, sub_wire23, sub_wire22, sub_wire21, sub_wire20, sub_wire19, sub_wire18, sub_wire17, sub_wire16, sub_wire15, sub_wire14, sub_wire13, sub_wire12, sub_wire11, sub_wire10, sub_wire9, sub_wire8, sub_wire7, sub_wire6, sub_wire5, sub_wire4, sub_wire3, sub_wire2, sub_wire0};
	wire [0:0] sub_wire66 = sub_wire65[0:0];
	wire  result = sub_wire66;

	Chowdhury_LPM_1Bit64x1Mux_Dec7_mux	Chowdhury_LPM_1Bit64x1Mux_Dec7_mux_component (
				.data (sub_wire1),
				.sel (sel),
				.result (sub_wire65));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: new_diagram STRING "1"
// Retrieval info: LIBRARY: lpm lpm.lpm_components.all
// Retrieval info: CONSTANT: LPM_SIZE NUMERIC "64"
// Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_MUX"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "1"
// Retrieval info: CONSTANT: LPM_WIDTHS NUMERIC "6"
// Retrieval info: USED_PORT: data0 0 0 0 0 INPUT NODEFVAL "data0"
// Retrieval info: USED_PORT: data1 0 0 0 0 INPUT NODEFVAL "data1"
// Retrieval info: USED_PORT: data10 0 0 0 0 INPUT NODEFVAL "data10"
// Retrieval info: USED_PORT: data11 0 0 0 0 INPUT NODEFVAL "data11"
// Retrieval info: USED_PORT: data12 0 0 0 0 INPUT NODEFVAL "data12"
// Retrieval info: USED_PORT: data13 0 0 0 0 INPUT NODEFVAL "data13"
// Retrieval info: USED_PORT: data14 0 0 0 0 INPUT NODEFVAL "data14"
// Retrieval info: USED_PORT: data15 0 0 0 0 INPUT NODEFVAL "data15"
// Retrieval info: USED_PORT: data16 0 0 0 0 INPUT NODEFVAL "data16"
// Retrieval info: USED_PORT: data17 0 0 0 0 INPUT NODEFVAL "data17"
// Retrieval info: USED_PORT: data18 0 0 0 0 INPUT NODEFVAL "data18"
// Retrieval info: USED_PORT: data19 0 0 0 0 INPUT NODEFVAL "data19"
// Retrieval info: USED_PORT: data2 0 0 0 0 INPUT NODEFVAL "data2"
// Retrieval info: USED_PORT: data20 0 0 0 0 INPUT NODEFVAL "data20"
// Retrieval info: USED_PORT: data21 0 0 0 0 INPUT NODEFVAL "data21"
// Retrieval info: USED_PORT: data22 0 0 0 0 INPUT NODEFVAL "data22"
// Retrieval info: USED_PORT: data23 0 0 0 0 INPUT NODEFVAL "data23"
// Retrieval info: USED_PORT: data24 0 0 0 0 INPUT NODEFVAL "data24"
// Retrieval info: USED_PORT: data25 0 0 0 0 INPUT NODEFVAL "data25"
// Retrieval info: USED_PORT: data26 0 0 0 0 INPUT NODEFVAL "data26"
// Retrieval info: USED_PORT: data27 0 0 0 0 INPUT NODEFVAL "data27"
// Retrieval info: USED_PORT: data28 0 0 0 0 INPUT NODEFVAL "data28"
// Retrieval info: USED_PORT: data29 0 0 0 0 INPUT NODEFVAL "data29"
// Retrieval info: USED_PORT: data3 0 0 0 0 INPUT NODEFVAL "data3"
// Retrieval info: USED_PORT: data30 0 0 0 0 INPUT NODEFVAL "data30"
// Retrieval info: USED_PORT: data31 0 0 0 0 INPUT NODEFVAL "data31"
// Retrieval info: USED_PORT: data32 0 0 0 0 INPUT NODEFVAL "data32"
// Retrieval info: USED_PORT: data33 0 0 0 0 INPUT NODEFVAL "data33"
// Retrieval info: USED_PORT: data34 0 0 0 0 INPUT NODEFVAL "data34"
// Retrieval info: USED_PORT: data35 0 0 0 0 INPUT NODEFVAL "data35"
// Retrieval info: USED_PORT: data36 0 0 0 0 INPUT NODEFVAL "data36"
// Retrieval info: USED_PORT: data37 0 0 0 0 INPUT NODEFVAL "data37"
// Retrieval info: USED_PORT: data38 0 0 0 0 INPUT NODEFVAL "data38"
// Retrieval info: USED_PORT: data39 0 0 0 0 INPUT NODEFVAL "data39"
// Retrieval info: USED_PORT: data4 0 0 0 0 INPUT NODEFVAL "data4"
// Retrieval info: USED_PORT: data40 0 0 0 0 INPUT NODEFVAL "data40"
// Retrieval info: USED_PORT: data41 0 0 0 0 INPUT NODEFVAL "data41"
// Retrieval info: USED_PORT: data42 0 0 0 0 INPUT NODEFVAL "data42"
// Retrieval info: USED_PORT: data43 0 0 0 0 INPUT NODEFVAL "data43"
// Retrieval info: USED_PORT: data44 0 0 0 0 INPUT NODEFVAL "data44"
// Retrieval info: USED_PORT: data45 0 0 0 0 INPUT NODEFVAL "data45"
// Retrieval info: USED_PORT: data46 0 0 0 0 INPUT NODEFVAL "data46"
// Retrieval info: USED_PORT: data47 0 0 0 0 INPUT NODEFVAL "data47"
// Retrieval info: USED_PORT: data48 0 0 0 0 INPUT NODEFVAL "data48"
// Retrieval info: USED_PORT: data49 0 0 0 0 INPUT NODEFVAL "data49"
// Retrieval info: USED_PORT: data5 0 0 0 0 INPUT NODEFVAL "data5"
// Retrieval info: USED_PORT: data50 0 0 0 0 INPUT NODEFVAL "data50"
// Retrieval info: USED_PORT: data51 0 0 0 0 INPUT NODEFVAL "data51"
// Retrieval info: USED_PORT: data52 0 0 0 0 INPUT NODEFVAL "data52"
// Retrieval info: USED_PORT: data53 0 0 0 0 INPUT NODEFVAL "data53"
// Retrieval info: USED_PORT: data54 0 0 0 0 INPUT NODEFVAL "data54"
// Retrieval info: USED_PORT: data55 0 0 0 0 INPUT NODEFVAL "data55"
// Retrieval info: USED_PORT: data56 0 0 0 0 INPUT NODEFVAL "data56"
// Retrieval info: USED_PORT: data57 0 0 0 0 INPUT NODEFVAL "data57"
// Retrieval info: USED_PORT: data58 0 0 0 0 INPUT NODEFVAL "data58"
// Retrieval info: USED_PORT: data59 0 0 0 0 INPUT NODEFVAL "data59"
// Retrieval info: USED_PORT: data6 0 0 0 0 INPUT NODEFVAL "data6"
// Retrieval info: USED_PORT: data60 0 0 0 0 INPUT NODEFVAL "data60"
// Retrieval info: USED_PORT: data61 0 0 0 0 INPUT NODEFVAL "data61"
// Retrieval info: USED_PORT: data62 0 0 0 0 INPUT NODEFVAL "data62"
// Retrieval info: USED_PORT: data63 0 0 0 0 INPUT NODEFVAL "data63"
// Retrieval info: USED_PORT: data7 0 0 0 0 INPUT NODEFVAL "data7"
// Retrieval info: USED_PORT: data8 0 0 0 0 INPUT NODEFVAL "data8"
// Retrieval info: USED_PORT: data9 0 0 0 0 INPUT NODEFVAL "data9"
// Retrieval info: USED_PORT: result 0 0 0 0 OUTPUT NODEFVAL "result"
// Retrieval info: USED_PORT: sel 0 0 6 0 INPUT NODEFVAL "sel[5..0]"
// Retrieval info: CONNECT: @data 1 0 1 0 data0 0 0 0 0
// Retrieval info: CONNECT: @data 1 1 1 0 data1 0 0 0 0
// Retrieval info: CONNECT: @data 1 10 1 0 data10 0 0 0 0
// Retrieval info: CONNECT: @data 1 11 1 0 data11 0 0 0 0
// Retrieval info: CONNECT: @data 1 12 1 0 data12 0 0 0 0
// Retrieval info: CONNECT: @data 1 13 1 0 data13 0 0 0 0
// Retrieval info: CONNECT: @data 1 14 1 0 data14 0 0 0 0
// Retrieval info: CONNECT: @data 1 15 1 0 data15 0 0 0 0
// Retrieval info: CONNECT: @data 1 16 1 0 data16 0 0 0 0
// Retrieval info: CONNECT: @data 1 17 1 0 data17 0 0 0 0
// Retrieval info: CONNECT: @data 1 18 1 0 data18 0 0 0 0
// Retrieval info: CONNECT: @data 1 19 1 0 data19 0 0 0 0
// Retrieval info: CONNECT: @data 1 2 1 0 data2 0 0 0 0
// Retrieval info: CONNECT: @data 1 20 1 0 data20 0 0 0 0
// Retrieval info: CONNECT: @data 1 21 1 0 data21 0 0 0 0
// Retrieval info: CONNECT: @data 1 22 1 0 data22 0 0 0 0
// Retrieval info: CONNECT: @data 1 23 1 0 data23 0 0 0 0
// Retrieval info: CONNECT: @data 1 24 1 0 data24 0 0 0 0
// Retrieval info: CONNECT: @data 1 25 1 0 data25 0 0 0 0
// Retrieval info: CONNECT: @data 1 26 1 0 data26 0 0 0 0
// Retrieval info: CONNECT: @data 1 27 1 0 data27 0 0 0 0
// Retrieval info: CONNECT: @data 1 28 1 0 data28 0 0 0 0
// Retrieval info: CONNECT: @data 1 29 1 0 data29 0 0 0 0
// Retrieval info: CONNECT: @data 1 3 1 0 data3 0 0 0 0
// Retrieval info: CONNECT: @data 1 30 1 0 data30 0 0 0 0
// Retrieval info: CONNECT: @data 1 31 1 0 data31 0 0 0 0
// Retrieval info: CONNECT: @data 1 32 1 0 data32 0 0 0 0
// Retrieval info: CONNECT: @data 1 33 1 0 data33 0 0 0 0
// Retrieval info: CONNECT: @data 1 34 1 0 data34 0 0 0 0
// Retrieval info: CONNECT: @data 1 35 1 0 data35 0 0 0 0
// Retrieval info: CONNECT: @data 1 36 1 0 data36 0 0 0 0
// Retrieval info: CONNECT: @data 1 37 1 0 data37 0 0 0 0
// Retrieval info: CONNECT: @data 1 38 1 0 data38 0 0 0 0
// Retrieval info: CONNECT: @data 1 39 1 0 data39 0 0 0 0
// Retrieval info: CONNECT: @data 1 4 1 0 data4 0 0 0 0
// Retrieval info: CONNECT: @data 1 40 1 0 data40 0 0 0 0
// Retrieval info: CONNECT: @data 1 41 1 0 data41 0 0 0 0
// Retrieval info: CONNECT: @data 1 42 1 0 data42 0 0 0 0
// Retrieval info: CONNECT: @data 1 43 1 0 data43 0 0 0 0
// Retrieval info: CONNECT: @data 1 44 1 0 data44 0 0 0 0
// Retrieval info: CONNECT: @data 1 45 1 0 data45 0 0 0 0
// Retrieval info: CONNECT: @data 1 46 1 0 data46 0 0 0 0
// Retrieval info: CONNECT: @data 1 47 1 0 data47 0 0 0 0
// Retrieval info: CONNECT: @data 1 48 1 0 data48 0 0 0 0
// Retrieval info: CONNECT: @data 1 49 1 0 data49 0 0 0 0
// Retrieval info: CONNECT: @data 1 5 1 0 data5 0 0 0 0
// Retrieval info: CONNECT: @data 1 50 1 0 data50 0 0 0 0
// Retrieval info: CONNECT: @data 1 51 1 0 data51 0 0 0 0
// Retrieval info: CONNECT: @data 1 52 1 0 data52 0 0 0 0
// Retrieval info: CONNECT: @data 1 53 1 0 data53 0 0 0 0
// Retrieval info: CONNECT: @data 1 54 1 0 data54 0 0 0 0
// Retrieval info: CONNECT: @data 1 55 1 0 data55 0 0 0 0
// Retrieval info: CONNECT: @data 1 56 1 0 data56 0 0 0 0
// Retrieval info: CONNECT: @data 1 57 1 0 data57 0 0 0 0
// Retrieval info: CONNECT: @data 1 58 1 0 data58 0 0 0 0
// Retrieval info: CONNECT: @data 1 59 1 0 data59 0 0 0 0
// Retrieval info: CONNECT: @data 1 6 1 0 data6 0 0 0 0
// Retrieval info: CONNECT: @data 1 60 1 0 data60 0 0 0 0
// Retrieval info: CONNECT: @data 1 61 1 0 data61 0 0 0 0
// Retrieval info: CONNECT: @data 1 62 1 0 data62 0 0 0 0
// Retrieval info: CONNECT: @data 1 63 1 0 data63 0 0 0 0
// Retrieval info: CONNECT: @data 1 7 1 0 data7 0 0 0 0
// Retrieval info: CONNECT: @data 1 8 1 0 data8 0 0 0 0
// Retrieval info: CONNECT: @data 1 9 1 0 data9 0 0 0 0
// Retrieval info: CONNECT: @sel 0 0 6 0 sel 0 0 6 0
// Retrieval info: CONNECT: result 0 0 0 0 @result 0 0 1 0
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_1Bit64x1Mux_Dec7.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_1Bit64x1Mux_Dec7.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_1Bit64x1Mux_Dec7.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_1Bit64x1Mux_Dec7.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_1Bit64x1Mux_Dec7_inst.vhd FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_1Bit64x1Mux_Dec7_syn.v TRUE
// Retrieval info: LIB_FILE: lpm
