// megafunction wizard: %LPM_DECODE%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: LPM_DECODE 

// ============================================================
// File Name: Chowdhury_LPM_5x32Decoder_Dec7.v
// Megafunction Name(s):
// 			LPM_DECODE
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 16.0.0 Build 211 04/27/2016 SJ Lite Edition
// ************************************************************


//Copyright (C) 1991-2016 Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus Prime License Agreement,
//the Altera MegaCore Function License Agreement, or other 
//applicable license agreement, including, without limitation, 
//that your use is for the sole purpose of programming logic 
//devices manufactured by Altera and sold by Altera or its 
//authorized distributors.  Please refer to the applicable 
//agreement for further details.


//lpm_decode DEVICE_FAMILY="Cyclone V" LPM_DECODES=32 LPM_WIDTH=5 data eq
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_lpm_decode 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = lut 36 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  Chowdhury_LPM_5x32Decoder_Dec7_decode
	( 
	data,
	eq) /* synthesis synthesis_clearbox=1 */;
	input   [4:0]  data;
	output   [31:0]  eq;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [4:0]  data;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [4:0]  data_wire;
	wire  [31:0]  eq_node;
	wire  [31:0]  eq_wire;
	wire  [2:0]  w_anode106w;
	wire  [3:0]  w_anode116w;
	wire  [3:0]  w_anode127w;
	wire  [3:0]  w_anode137w;
	wire  [3:0]  w_anode147w;
	wire  [3:0]  w_anode157w;
	wire  [3:0]  w_anode167w;
	wire  [3:0]  w_anode177w;
	wire  [3:0]  w_anode17w;
	wire  [3:0]  w_anode187w;
	wire  [2:0]  w_anode198w;
	wire  [3:0]  w_anode208w;
	wire  [3:0]  w_anode219w;
	wire  [3:0]  w_anode229w;
	wire  [3:0]  w_anode239w;
	wire  [3:0]  w_anode249w;
	wire  [3:0]  w_anode259w;
	wire  [3:0]  w_anode269w;
	wire  [3:0]  w_anode279w;
	wire  [2:0]  w_anode290w;
	wire  [3:0]  w_anode300w;
	wire  [3:0]  w_anode311w;
	wire  [3:0]  w_anode321w;
	wire  [3:0]  w_anode331w;
	wire  [3:0]  w_anode341w;
	wire  [3:0]  w_anode34w;
	wire  [3:0]  w_anode351w;
	wire  [3:0]  w_anode361w;
	wire  [3:0]  w_anode371w;
	wire  [2:0]  w_anode3w;
	wire  [3:0]  w_anode44w;
	wire  [3:0]  w_anode54w;
	wire  [3:0]  w_anode64w;
	wire  [3:0]  w_anode74w;
	wire  [3:0]  w_anode84w;
	wire  [3:0]  w_anode94w;
	wire  [2:0]  w_data1w;

	assign
		data_wire = data,
		eq = eq_node,
		eq_node = eq_wire[31:0],
		eq_wire = {{w_anode371w[3], w_anode361w[3], w_anode351w[3], w_anode341w[3], w_anode331w[3], w_anode321w[3], w_anode311w[3], w_anode300w[3]}, {w_anode279w[3], w_anode269w[3], w_anode259w[3], w_anode249w[3], w_anode239w[3], w_anode229w[3], w_anode219w[3], w_anode208w[3]}, {w_anode187w[3], w_anode177w[3], w_anode167w[3], w_anode157w[3], w_anode147w[3], w_anode137w[3], w_anode127w[3], w_anode116w[3]}, {w_anode94w[3], w_anode84w[3], w_anode74w[3], w_anode64w[3], w_anode54w[3], w_anode44w[3], w_anode34w[3], w_anode17w[3]}},
		w_anode106w = {(w_anode106w[1] & (~ data_wire[4])), (w_anode106w[0] & data_wire[3]), 1'b1},
		w_anode116w = {(w_anode116w[2] & (~ w_data1w[2])), (w_anode116w[1] & (~ w_data1w[1])), (w_anode116w[0] & (~ w_data1w[0])), w_anode106w[2]},
		w_anode127w = {(w_anode127w[2] & (~ w_data1w[2])), (w_anode127w[1] & (~ w_data1w[1])), (w_anode127w[0] & w_data1w[0]), w_anode106w[2]},
		w_anode137w = {(w_anode137w[2] & (~ w_data1w[2])), (w_anode137w[1] & w_data1w[1]), (w_anode137w[0] & (~ w_data1w[0])), w_anode106w[2]},
		w_anode147w = {(w_anode147w[2] & (~ w_data1w[2])), (w_anode147w[1] & w_data1w[1]), (w_anode147w[0] & w_data1w[0]), w_anode106w[2]},
		w_anode157w = {(w_anode157w[2] & w_data1w[2]), (w_anode157w[1] & (~ w_data1w[1])), (w_anode157w[0] & (~ w_data1w[0])), w_anode106w[2]},
		w_anode167w = {(w_anode167w[2] & w_data1w[2]), (w_anode167w[1] & (~ w_data1w[1])), (w_anode167w[0] & w_data1w[0]), w_anode106w[2]},
		w_anode177w = {(w_anode177w[2] & w_data1w[2]), (w_anode177w[1] & w_data1w[1]), (w_anode177w[0] & (~ w_data1w[0])), w_anode106w[2]},
		w_anode17w = {(w_anode17w[2] & (~ w_data1w[2])), (w_anode17w[1] & (~ w_data1w[1])), (w_anode17w[0] & (~ w_data1w[0])), w_anode3w[2]},
		w_anode187w = {(w_anode187w[2] & w_data1w[2]), (w_anode187w[1] & w_data1w[1]), (w_anode187w[0] & w_data1w[0]), w_anode106w[2]},
		w_anode198w = {(w_anode198w[1] & data_wire[4]), (w_anode198w[0] & (~ data_wire[3])), 1'b1},
		w_anode208w = {(w_anode208w[2] & (~ w_data1w[2])), (w_anode208w[1] & (~ w_data1w[1])), (w_anode208w[0] & (~ w_data1w[0])), w_anode198w[2]},
		w_anode219w = {(w_anode219w[2] & (~ w_data1w[2])), (w_anode219w[1] & (~ w_data1w[1])), (w_anode219w[0] & w_data1w[0]), w_anode198w[2]},
		w_anode229w = {(w_anode229w[2] & (~ w_data1w[2])), (w_anode229w[1] & w_data1w[1]), (w_anode229w[0] & (~ w_data1w[0])), w_anode198w[2]},
		w_anode239w = {(w_anode239w[2] & (~ w_data1w[2])), (w_anode239w[1] & w_data1w[1]), (w_anode239w[0] & w_data1w[0]), w_anode198w[2]},
		w_anode249w = {(w_anode249w[2] & w_data1w[2]), (w_anode249w[1] & (~ w_data1w[1])), (w_anode249w[0] & (~ w_data1w[0])), w_anode198w[2]},
		w_anode259w = {(w_anode259w[2] & w_data1w[2]), (w_anode259w[1] & (~ w_data1w[1])), (w_anode259w[0] & w_data1w[0]), w_anode198w[2]},
		w_anode269w = {(w_anode269w[2] & w_data1w[2]), (w_anode269w[1] & w_data1w[1]), (w_anode269w[0] & (~ w_data1w[0])), w_anode198w[2]},
		w_anode279w = {(w_anode279w[2] & w_data1w[2]), (w_anode279w[1] & w_data1w[1]), (w_anode279w[0] & w_data1w[0]), w_anode198w[2]},
		w_anode290w = {(w_anode290w[1] & data_wire[4]), (w_anode290w[0] & data_wire[3]), 1'b1},
		w_anode300w = {(w_anode300w[2] & (~ w_data1w[2])), (w_anode300w[1] & (~ w_data1w[1])), (w_anode300w[0] & (~ w_data1w[0])), w_anode290w[2]},
		w_anode311w = {(w_anode311w[2] & (~ w_data1w[2])), (w_anode311w[1] & (~ w_data1w[1])), (w_anode311w[0] & w_data1w[0]), w_anode290w[2]},
		w_anode321w = {(w_anode321w[2] & (~ w_data1w[2])), (w_anode321w[1] & w_data1w[1]), (w_anode321w[0] & (~ w_data1w[0])), w_anode290w[2]},
		w_anode331w = {(w_anode331w[2] & (~ w_data1w[2])), (w_anode331w[1] & w_data1w[1]), (w_anode331w[0] & w_data1w[0]), w_anode290w[2]},
		w_anode341w = {(w_anode341w[2] & w_data1w[2]), (w_anode341w[1] & (~ w_data1w[1])), (w_anode341w[0] & (~ w_data1w[0])), w_anode290w[2]},
		w_anode34w = {(w_anode34w[2] & (~ w_data1w[2])), (w_anode34w[1] & (~ w_data1w[1])), (w_anode34w[0] & w_data1w[0]), w_anode3w[2]},
		w_anode351w = {(w_anode351w[2] & w_data1w[2]), (w_anode351w[1] & (~ w_data1w[1])), (w_anode351w[0] & w_data1w[0]), w_anode290w[2]},
		w_anode361w = {(w_anode361w[2] & w_data1w[2]), (w_anode361w[1] & w_data1w[1]), (w_anode361w[0] & (~ w_data1w[0])), w_anode290w[2]},
		w_anode371w = {(w_anode371w[2] & w_data1w[2]), (w_anode371w[1] & w_data1w[1]), (w_anode371w[0] & w_data1w[0]), w_anode290w[2]},
		w_anode3w = {(w_anode3w[1] & (~ data_wire[4])), (w_anode3w[0] & (~ data_wire[3])), 1'b1},
		w_anode44w = {(w_anode44w[2] & (~ w_data1w[2])), (w_anode44w[1] & w_data1w[1]), (w_anode44w[0] & (~ w_data1w[0])), w_anode3w[2]},
		w_anode54w = {(w_anode54w[2] & (~ w_data1w[2])), (w_anode54w[1] & w_data1w[1]), (w_anode54w[0] & w_data1w[0]), w_anode3w[2]},
		w_anode64w = {(w_anode64w[2] & w_data1w[2]), (w_anode64w[1] & (~ w_data1w[1])), (w_anode64w[0] & (~ w_data1w[0])), w_anode3w[2]},
		w_anode74w = {(w_anode74w[2] & w_data1w[2]), (w_anode74w[1] & (~ w_data1w[1])), (w_anode74w[0] & w_data1w[0]), w_anode3w[2]},
		w_anode84w = {(w_anode84w[2] & w_data1w[2]), (w_anode84w[1] & w_data1w[1]), (w_anode84w[0] & (~ w_data1w[0])), w_anode3w[2]},
		w_anode94w = {(w_anode94w[2] & w_data1w[2]), (w_anode94w[1] & w_data1w[1]), (w_anode94w[0] & w_data1w[0]), w_anode3w[2]},
		w_data1w = data_wire[2:0];
endmodule //Chowdhury_LPM_5x32Decoder_Dec7_decode
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module Chowdhury_LPM_5x32Decoder_Dec7 (
	data,
	eq0,
	eq1,
	eq10,
	eq11,
	eq12,
	eq13,
	eq14,
	eq15,
	eq16,
	eq17,
	eq18,
	eq19,
	eq2,
	eq20,
	eq21,
	eq22,
	eq23,
	eq24,
	eq25,
	eq26,
	eq27,
	eq28,
	eq29,
	eq3,
	eq30,
	eq31,
	eq4,
	eq5,
	eq6,
	eq7,
	eq8,
	eq9)/* synthesis synthesis_clearbox = 1 */;

	input	[4:0]  data;
	output	  eq0;
	output	  eq1;
	output	  eq10;
	output	  eq11;
	output	  eq12;
	output	  eq13;
	output	  eq14;
	output	  eq15;
	output	  eq16;
	output	  eq17;
	output	  eq18;
	output	  eq19;
	output	  eq2;
	output	  eq20;
	output	  eq21;
	output	  eq22;
	output	  eq23;
	output	  eq24;
	output	  eq25;
	output	  eq26;
	output	  eq27;
	output	  eq28;
	output	  eq29;
	output	  eq3;
	output	  eq30;
	output	  eq31;
	output	  eq4;
	output	  eq5;
	output	  eq6;
	output	  eq7;
	output	  eq8;
	output	  eq9;

	wire [31:0] sub_wire0;
	wire [9:9] sub_wire32 = sub_wire0[9:9];
	wire [8:8] sub_wire31 = sub_wire0[8:8];
	wire [7:7] sub_wire30 = sub_wire0[7:7];
	wire [6:6] sub_wire29 = sub_wire0[6:6];
	wire [5:5] sub_wire28 = sub_wire0[5:5];
	wire [4:4] sub_wire27 = sub_wire0[4:4];
	wire [31:31] sub_wire26 = sub_wire0[31:31];
	wire [30:30] sub_wire25 = sub_wire0[30:30];
	wire [3:3] sub_wire24 = sub_wire0[3:3];
	wire [29:29] sub_wire23 = sub_wire0[29:29];
	wire [28:28] sub_wire22 = sub_wire0[28:28];
	wire [27:27] sub_wire21 = sub_wire0[27:27];
	wire [26:26] sub_wire20 = sub_wire0[26:26];
	wire [25:25] sub_wire19 = sub_wire0[25:25];
	wire [24:24] sub_wire18 = sub_wire0[24:24];
	wire [23:23] sub_wire17 = sub_wire0[23:23];
	wire [22:22] sub_wire16 = sub_wire0[22:22];
	wire [21:21] sub_wire15 = sub_wire0[21:21];
	wire [20:20] sub_wire14 = sub_wire0[20:20];
	wire [2:2] sub_wire13 = sub_wire0[2:2];
	wire [19:19] sub_wire12 = sub_wire0[19:19];
	wire [18:18] sub_wire11 = sub_wire0[18:18];
	wire [17:17] sub_wire10 = sub_wire0[17:17];
	wire [16:16] sub_wire9 = sub_wire0[16:16];
	wire [15:15] sub_wire8 = sub_wire0[15:15];
	wire [14:14] sub_wire7 = sub_wire0[14:14];
	wire [13:13] sub_wire6 = sub_wire0[13:13];
	wire [12:12] sub_wire5 = sub_wire0[12:12];
	wire [11:11] sub_wire4 = sub_wire0[11:11];
	wire [10:10] sub_wire3 = sub_wire0[10:10];
	wire [1:1] sub_wire2 = sub_wire0[1:1];
	wire [0:0] sub_wire1 = sub_wire0[0:0];
	wire  eq0 = sub_wire1;
	wire  eq1 = sub_wire2;
	wire  eq10 = sub_wire3;
	wire  eq11 = sub_wire4;
	wire  eq12 = sub_wire5;
	wire  eq13 = sub_wire6;
	wire  eq14 = sub_wire7;
	wire  eq15 = sub_wire8;
	wire  eq16 = sub_wire9;
	wire  eq17 = sub_wire10;
	wire  eq18 = sub_wire11;
	wire  eq19 = sub_wire12;
	wire  eq2 = sub_wire13;
	wire  eq20 = sub_wire14;
	wire  eq21 = sub_wire15;
	wire  eq22 = sub_wire16;
	wire  eq23 = sub_wire17;
	wire  eq24 = sub_wire18;
	wire  eq25 = sub_wire19;
	wire  eq26 = sub_wire20;
	wire  eq27 = sub_wire21;
	wire  eq28 = sub_wire22;
	wire  eq29 = sub_wire23;
	wire  eq3 = sub_wire24;
	wire  eq30 = sub_wire25;
	wire  eq31 = sub_wire26;
	wire  eq4 = sub_wire27;
	wire  eq5 = sub_wire28;
	wire  eq6 = sub_wire29;
	wire  eq7 = sub_wire30;
	wire  eq8 = sub_wire31;
	wire  eq9 = sub_wire32;

	Chowdhury_LPM_5x32Decoder_Dec7_decode	Chowdhury_LPM_5x32Decoder_Dec7_decode_component (
				.data (data),
				.eq (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: BaseDec NUMERIC "1"
// Retrieval info: PRIVATE: EnableInput NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: PRIVATE: LPM_PIPELINE NUMERIC "0"
// Retrieval info: PRIVATE: Latency NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: aclr NUMERIC "0"
// Retrieval info: PRIVATE: clken NUMERIC "0"
// Retrieval info: PRIVATE: eq0 NUMERIC "1"
// Retrieval info: PRIVATE: eq1 NUMERIC "1"
// Retrieval info: PRIVATE: eq10 NUMERIC "1"
// Retrieval info: PRIVATE: eq11 NUMERIC "1"
// Retrieval info: PRIVATE: eq12 NUMERIC "1"
// Retrieval info: PRIVATE: eq13 NUMERIC "1"
// Retrieval info: PRIVATE: eq14 NUMERIC "1"
// Retrieval info: PRIVATE: eq15 NUMERIC "1"
// Retrieval info: PRIVATE: eq16 NUMERIC "1"
// Retrieval info: PRIVATE: eq17 NUMERIC "1"
// Retrieval info: PRIVATE: eq18 NUMERIC "1"
// Retrieval info: PRIVATE: eq19 NUMERIC "1"
// Retrieval info: PRIVATE: eq2 NUMERIC "1"
// Retrieval info: PRIVATE: eq20 NUMERIC "1"
// Retrieval info: PRIVATE: eq21 NUMERIC "1"
// Retrieval info: PRIVATE: eq22 NUMERIC "1"
// Retrieval info: PRIVATE: eq23 NUMERIC "1"
// Retrieval info: PRIVATE: eq24 NUMERIC "1"
// Retrieval info: PRIVATE: eq25 NUMERIC "1"
// Retrieval info: PRIVATE: eq26 NUMERIC "1"
// Retrieval info: PRIVATE: eq27 NUMERIC "1"
// Retrieval info: PRIVATE: eq28 NUMERIC "1"
// Retrieval info: PRIVATE: eq29 NUMERIC "1"
// Retrieval info: PRIVATE: eq3 NUMERIC "1"
// Retrieval info: PRIVATE: eq30 NUMERIC "1"
// Retrieval info: PRIVATE: eq31 NUMERIC "1"
// Retrieval info: PRIVATE: eq4 NUMERIC "1"
// Retrieval info: PRIVATE: eq5 NUMERIC "1"
// Retrieval info: PRIVATE: eq6 NUMERIC "1"
// Retrieval info: PRIVATE: eq7 NUMERIC "1"
// Retrieval info: PRIVATE: eq8 NUMERIC "1"
// Retrieval info: PRIVATE: eq9 NUMERIC "1"
// Retrieval info: PRIVATE: nBit NUMERIC "5"
// Retrieval info: PRIVATE: new_diagram STRING "1"
// Retrieval info: LIBRARY: lpm lpm.lpm_components.all
// Retrieval info: CONSTANT: LPM_DECODES NUMERIC "32"
// Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_DECODE"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "5"
// Retrieval info: USED_PORT: @eq 0 0 32 0 OUTPUT NODEFVAL "@eq[31..0]"
// Retrieval info: USED_PORT: data 0 0 5 0 INPUT NODEFVAL "data[4..0]"
// Retrieval info: USED_PORT: eq0 0 0 0 0 OUTPUT NODEFVAL "eq0"
// Retrieval info: USED_PORT: eq1 0 0 0 0 OUTPUT NODEFVAL "eq1"
// Retrieval info: USED_PORT: eq10 0 0 0 0 OUTPUT NODEFVAL "eq10"
// Retrieval info: USED_PORT: eq11 0 0 0 0 OUTPUT NODEFVAL "eq11"
// Retrieval info: USED_PORT: eq12 0 0 0 0 OUTPUT NODEFVAL "eq12"
// Retrieval info: USED_PORT: eq13 0 0 0 0 OUTPUT NODEFVAL "eq13"
// Retrieval info: USED_PORT: eq14 0 0 0 0 OUTPUT NODEFVAL "eq14"
// Retrieval info: USED_PORT: eq15 0 0 0 0 OUTPUT NODEFVAL "eq15"
// Retrieval info: USED_PORT: eq16 0 0 0 0 OUTPUT NODEFVAL "eq16"
// Retrieval info: USED_PORT: eq17 0 0 0 0 OUTPUT NODEFVAL "eq17"
// Retrieval info: USED_PORT: eq18 0 0 0 0 OUTPUT NODEFVAL "eq18"
// Retrieval info: USED_PORT: eq19 0 0 0 0 OUTPUT NODEFVAL "eq19"
// Retrieval info: USED_PORT: eq2 0 0 0 0 OUTPUT NODEFVAL "eq2"
// Retrieval info: USED_PORT: eq20 0 0 0 0 OUTPUT NODEFVAL "eq20"
// Retrieval info: USED_PORT: eq21 0 0 0 0 OUTPUT NODEFVAL "eq21"
// Retrieval info: USED_PORT: eq22 0 0 0 0 OUTPUT NODEFVAL "eq22"
// Retrieval info: USED_PORT: eq23 0 0 0 0 OUTPUT NODEFVAL "eq23"
// Retrieval info: USED_PORT: eq24 0 0 0 0 OUTPUT NODEFVAL "eq24"
// Retrieval info: USED_PORT: eq25 0 0 0 0 OUTPUT NODEFVAL "eq25"
// Retrieval info: USED_PORT: eq26 0 0 0 0 OUTPUT NODEFVAL "eq26"
// Retrieval info: USED_PORT: eq27 0 0 0 0 OUTPUT NODEFVAL "eq27"
// Retrieval info: USED_PORT: eq28 0 0 0 0 OUTPUT NODEFVAL "eq28"
// Retrieval info: USED_PORT: eq29 0 0 0 0 OUTPUT NODEFVAL "eq29"
// Retrieval info: USED_PORT: eq3 0 0 0 0 OUTPUT NODEFVAL "eq3"
// Retrieval info: USED_PORT: eq30 0 0 0 0 OUTPUT NODEFVAL "eq30"
// Retrieval info: USED_PORT: eq31 0 0 0 0 OUTPUT NODEFVAL "eq31"
// Retrieval info: USED_PORT: eq4 0 0 0 0 OUTPUT NODEFVAL "eq4"
// Retrieval info: USED_PORT: eq5 0 0 0 0 OUTPUT NODEFVAL "eq5"
// Retrieval info: USED_PORT: eq6 0 0 0 0 OUTPUT NODEFVAL "eq6"
// Retrieval info: USED_PORT: eq7 0 0 0 0 OUTPUT NODEFVAL "eq7"
// Retrieval info: USED_PORT: eq8 0 0 0 0 OUTPUT NODEFVAL "eq8"
// Retrieval info: USED_PORT: eq9 0 0 0 0 OUTPUT NODEFVAL "eq9"
// Retrieval info: CONNECT: @data 0 0 5 0 data 0 0 5 0
// Retrieval info: CONNECT: eq0 0 0 0 0 @eq 0 0 1 0
// Retrieval info: CONNECT: eq1 0 0 0 0 @eq 0 0 1 1
// Retrieval info: CONNECT: eq10 0 0 0 0 @eq 0 0 1 10
// Retrieval info: CONNECT: eq11 0 0 0 0 @eq 0 0 1 11
// Retrieval info: CONNECT: eq12 0 0 0 0 @eq 0 0 1 12
// Retrieval info: CONNECT: eq13 0 0 0 0 @eq 0 0 1 13
// Retrieval info: CONNECT: eq14 0 0 0 0 @eq 0 0 1 14
// Retrieval info: CONNECT: eq15 0 0 0 0 @eq 0 0 1 15
// Retrieval info: CONNECT: eq16 0 0 0 0 @eq 0 0 1 16
// Retrieval info: CONNECT: eq17 0 0 0 0 @eq 0 0 1 17
// Retrieval info: CONNECT: eq18 0 0 0 0 @eq 0 0 1 18
// Retrieval info: CONNECT: eq19 0 0 0 0 @eq 0 0 1 19
// Retrieval info: CONNECT: eq2 0 0 0 0 @eq 0 0 1 2
// Retrieval info: CONNECT: eq20 0 0 0 0 @eq 0 0 1 20
// Retrieval info: CONNECT: eq21 0 0 0 0 @eq 0 0 1 21
// Retrieval info: CONNECT: eq22 0 0 0 0 @eq 0 0 1 22
// Retrieval info: CONNECT: eq23 0 0 0 0 @eq 0 0 1 23
// Retrieval info: CONNECT: eq24 0 0 0 0 @eq 0 0 1 24
// Retrieval info: CONNECT: eq25 0 0 0 0 @eq 0 0 1 25
// Retrieval info: CONNECT: eq26 0 0 0 0 @eq 0 0 1 26
// Retrieval info: CONNECT: eq27 0 0 0 0 @eq 0 0 1 27
// Retrieval info: CONNECT: eq28 0 0 0 0 @eq 0 0 1 28
// Retrieval info: CONNECT: eq29 0 0 0 0 @eq 0 0 1 29
// Retrieval info: CONNECT: eq3 0 0 0 0 @eq 0 0 1 3
// Retrieval info: CONNECT: eq30 0 0 0 0 @eq 0 0 1 30
// Retrieval info: CONNECT: eq31 0 0 0 0 @eq 0 0 1 31
// Retrieval info: CONNECT: eq4 0 0 0 0 @eq 0 0 1 4
// Retrieval info: CONNECT: eq5 0 0 0 0 @eq 0 0 1 5
// Retrieval info: CONNECT: eq6 0 0 0 0 @eq 0 0 1 6
// Retrieval info: CONNECT: eq7 0 0 0 0 @eq 0 0 1 7
// Retrieval info: CONNECT: eq8 0 0 0 0 @eq 0 0 1 8
// Retrieval info: CONNECT: eq9 0 0 0 0 @eq 0 0 1 9
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_5x32Decoder_Dec7.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_5x32Decoder_Dec7.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_5x32Decoder_Dec7.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_5x32Decoder_Dec7.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_5x32Decoder_Dec7_inst.vhd FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Chowdhury_LPM_5x32Decoder_Dec7_syn.v TRUE
// Retrieval info: LIB_FILE: lpm
